device: cuda
model: adult_cls
trainer: online_dytab_trainer
latent_dim: 5
num_hash: 3
num_bucket: 5
num_weight: 1
num_discrete: 1
num_continuous: 0
loss: nelbo_bce
optim: adam
learning_rate: 0.01
l2: 0.
ini_task_epoch: 100
epoch: 15
batch_size: 128
num_data_worker: 4
num_task: 300
exp_path: 
  results/mushroom_online/
